server: 
   port: 18081
   
spring:
   profiles: 
      active: dev
   application: 
      name: message

mybatis: 
   configuration: 
      map-underscore-to-camel-case: true
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.jacken.messagesms.domain
